name: Generate contribution snake SVG

on:
  schedule:
    - cron: '0 0 * * *'  # todo dia meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Download github-contribution-grid-snake zip with wget
      run: |
        wget --tries=3 --timeout=20 https://github.com/IonicaBizau/github-contribution-grid-snake/archive/refs/heads/main.zip -O snake.zip
        echo "Downloaded file size:"
        ls -lh snake.zip
        if [ $(stat -c%s snake.zip) -lt 1000 ]; then
          echo "File too small, download probably failed."
          exit 1
        fi

    - name: Unzip downloaded file
      run: unzip snake.zip

    - name: Generate SVG
      run: |
        node github-contribution-grid-snake-main/index.js -u ${{ github.repository_owner }} -o github-contribution-grid-snake.svg

    - name: Switch to output branch
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git checkout -B output

    - name: Move SVG and commit
      run: |
        mv github-contribution-grid-snake.svg .
        git add github-contribution-grid-snake.svg
        git commit -m "Update snake SVG" || echo "No changes to commit"
        git push origin output --force

