name: Generate contribution snake SVG

on:
  schedule:
    - cron: '0 0 * * *'  # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install github-contribution-grid-snake

    - name: Run snake generator
      run: node .github/scripts/generate-snake.js ${{ github.repository_owner }}

    - name: Commit and push SVG
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add github-contribution-grid-snake.svg
        git commit -m "Update snake SVG" || echo "No changes to commit"
        git push
